name: Test build and commands with ubuntu-18.04

on: 
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      if: github.event_name == 'pull_request'
      run: echo This event is a pull request. Test build ./ld init.


    - name: Get versions of Docker and docker-compose
      run: |
        echo "NEXT: Wait for docker to wake up"
        while ! docker system info > /dev/null 2>&1; do docker system info && ROUND=1 && echo "Waiting Docker.app to start, round ${ROUND}" && sleep 2 && (( ROUND + 1 )) ; done
        echo 'Docker.app should be now running...'
        which docker || echo 'no docker in path'
        [ -f /usr/bin/docker ] || exit 1
        docker system info
        docker ps 
        docker-compose --version

    - name: Install Ruby
      run: |
        sudo apt-get update
        sudo apt --fix-missing install ruby-full
        which gem

    - name: Install docker-sync (depencency)
      run: |
        sudo gem install docker-sync
        which docker-sync


    - name: List what is in the project folder.
      run: ls -lha

    - name: Check the type of ld
      run: file ld

    - name: Run init and see where it gets us
      run:  ./ld init

